package com.github.yferras.javartint.core.function;

/*
 * #%L
 * Crow JavArtInt Core
 * %%
 * Copyright (C) 2014 - 2015 Eng. Ferrás Cecilio, Yeinier
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public
 * License along with this program.  If not, see
 * <http://www.gnu.org/licenses/gpl-3.0.html>.
 * #L%
 */

/**
 * Interface to create generator functions.
 *
 * @param <R> Type of result
 * @author Eng. Ferrás Cecilio, Yeinier
 * @version 0.0.1
 * @since 1.1.0
 */
public interface GeneratorFunction<R> extends Function<R, Void[]> {

    /**
     * {@inheritDoc}
     * <p/>
     * This method not need params. It can be used to generate instances of type of {@code R}
     */
    @Override
    R evaluate(Void... params);

    /**
     * Gets the item class generated by this function.
     *
     * @return the class of generated item
     */
    Class<R> getItemGeneratedClass();
}
